services:
  webapitru:
    image: ${DOCKER_REGISTRY-}webapitru
    build:
      context: .
      dockerfile: WebApiTRU/Dockerfile

  # blazorapp:
  #     build: ..
  #     ports:
  #       - 6943:8080
  #     environment:
  #       - ASPNETCORE_ENVIRONMENT=Development
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
