--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Debian 15.13-1.pgdg120+1)
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
--SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: DorianTRU; Type: SCHEMA; Schema: -; Owner: username
--

CREATE SCHEMA "DorianTRU";


ALTER SCHEMA "DorianTRU" OWNER TO username;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: concert; Type: TABLE; Schema: DorianTRU; Owner: username
--

CREATE TABLE "DorianTRU".concert (
    id integer NOT NULL,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone,
    event_name character varying(60) NOT NULL,
    description character varying(300)
);


ALTER TABLE "DorianTRU".concert OWNER TO username;

--
-- Name: concert_id_seq; Type: SEQUENCE; Schema: DorianTRU; Owner: username
--

ALTER TABLE "DorianTRU".concert ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "DorianTRU".concert_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ticket; Type: TABLE; Schema: DorianTRU; Owner: username
--

CREATE TABLE "DorianTRU".ticket (
    id integer NOT NULL,
    qrhash character varying(16) NOT NULL,
    email character varying(40),
    concert_id integer,
    timescanned timestamp without time zone
);


ALTER TABLE "DorianTRU".ticket OWNER TO username;

--
-- Name: ticket_id_seq; Type: SEQUENCE; Schema: DorianTRU; Owner: username
--

ALTER TABLE "DorianTRU".ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "DorianTRU".ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: username
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO username;

--
-- Data for Name: concert; Type: TABLE DATA; Schema: DorianTRU; Owner: username
--

COPY "DorianTRU".concert (id, start_time, end_time, event_name, description) FROM stdin;
\.


--
-- Data for Name: ticket; Type: TABLE DATA; Schema: DorianTRU; Owner: username
--

COPY "DorianTRU".ticket (id, qrhash, email, concert_id, timescanned) FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: username
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240930051631_DorianTRU	8.0.8
20240930062358_SerialIdsHopefully	8.0.8
\.


--
-- Name: concert_id_seq; Type: SEQUENCE SET; Schema: DorianTRU; Owner: username
--

SELECT pg_catalog.setval('"DorianTRU".concert_id_seq', 1, false);


--
-- Name: ticket_id_seq; Type: SEQUENCE SET; Schema: DorianTRU; Owner: username
--

SELECT pg_catalog.setval('"DorianTRU".ticket_id_seq', 1, false);


--
-- Name: concert concert_pkey; Type: CONSTRAINT; Schema: DorianTRU; Owner: username
--

ALTER TABLE ONLY "DorianTRU".concert
    ADD CONSTRAINT concert_pkey PRIMARY KEY (id);


--
-- Name: ticket ticket_pkey; Type: CONSTRAINT; Schema: DorianTRU; Owner: username
--

ALTER TABLE ONLY "DorianTRU".ticket
    ADD CONSTRAINT ticket_pkey PRIMARY KEY (id);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: username
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_ticket_concert_id; Type: INDEX; Schema: DorianTRU; Owner: username
--

CREATE INDEX "IX_ticket_concert_id" ON "DorianTRU".ticket USING btree (concert_id);


--
-- Name: ticket ticket_concert_id_fkey; Type: FK CONSTRAINT; Schema: DorianTRU; Owner: username
--

ALTER TABLE ONLY "DorianTRU".ticket
    ADD CONSTRAINT ticket_concert_id_fkey FOREIGN KEY (concert_id) REFERENCES "DorianTRU".concert(id);


--
-- PostgreSQL database dump complete
--

